### ISSUE TITLE
add premium client functionality

### ISSUE THREAD

**Issue by Japoivvb** [reivaX1755/TiendaUF4#1]
1. before ask for client name in sale option, include a new question about if the client is premium or not.

-    if the answer is No, continue flow as is

-    if the answer is Yes, 

       create a premiumClient object which extends from Client, 
	   it has a points attribute and its pay method is the same as parent client but for each 10€ sales, it adds 1 point. e.g. if sale 35€, premiumClient gets 3 points.
       show its points earned after the sale total amount
	   
2. set issue label as enhancement to be tracked

3. commit message with verb + #numberIssue + details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by reivaX1755** [comment]
![Check #1 PremiumClient](https://github.com/reivaX1755/TiendaUF4/assets/163132865/b4bc829a-92ed-459e-b838-83836cd652e1)
![Check #1 NormalClient](https://github.com/reivaX1755/TiendaUF4/assets/163132865/5ee2afa9-1e7e-40ea-bf49-29cfbab6d5b1)

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok
5. ok
great job, you got +1 in UF4P1
